# Copyright (C) 2015 - Today: GRAP (http://www.grap.coop)
# @author: Julien WESTE
# @author: Sylvain LE GAL (https://twitter.com/legalsylvain)
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).

from odoo import _, api, fields, models
from odoo.exceptions import ValidationError


class WizardResPartnerAddExportCode(models.TransientModel):
    _name = "wizard.res.partner.add.export.code"
    _description = "Add Suffix for Partners Wizard"

    line_ids = fields.One2many(
        comodel_name="wizard.res.partner.add.export.code.line",
        inverse_name="wizard_id",
        string="Lines",
    )

    # View Section
    def button_affect_export_suffix(self):
        self.ensure_one()
        incorrect_lines = self.line_ids.filtered(lambda x: x.state != "ok")
        if incorrect_lines:
            raise ValidationError(
                _(
                    f"Unable to affect the account export code"
                    f" because {len(incorrect_lines)}"
                    f" over {len(self.line_ids)} are incorrect."
                )
            )
        for wizard in self:
            for line in wizard.line_ids.filtered(lambda x: x.export_suffix):
                line.partner_id.export_suffix = line.export_suffix

    def _check_incorrect_partners(self, partners):
        """Overload me for custom reasons"""
        global_partners = partners.filtered(lambda x: not x.company_id)

        if global_partners:
            raise ValidationError(
                _(
                    "Unable to use the wizard to guess export code for global partners"
                    "that are not related to a company.\n"
                    f"{','.join(global_partners.mapped('name'))}"
                )
            )

    # Overloading section
    @api.model
    def default_get(self, default_fields):
        ResPartner = self.env["res.partner"]

        res = super().default_get(default_fields)

        line_ids = []

        partners = ResPartner.browse(self.env.context.get("active_ids", []))
        self._check_incorrect_partners(partners)

        existing_suffixes = ResPartner._get_existing_export_suffixes(
            company_ids=partners.mapped("company_id").ids
        )

        for partner in partners:
            if partner.export_suffix:
                export_suffix = partner.export_suffix
            else:
                export_suffix = partner._guess_export_suffix(
                    existing_suffixes.get(partner.company_id.id, [])
                )
                # we add the suffix to the list of existing_suffix
                # to avoid to affect the same autogenerated suffix to
                # another partner
                if export_suffix:
                    existing_suffixes.setdefault(partner.company_id.id, [])
                    existing_suffixes[partner.company_id.id] += [export_suffix]
            line_vals = {
                "partner_id": partner.id,
                "company_id": partner.company_id.id,
                "export_suffix": export_suffix,
                "state": export_suffix and "ok" or "empty",
            }
            line_ids.append((0, 0, line_vals))
        res.update({"line_ids": line_ids})
        return res
